version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=0
      - SECRET_KEY=your_secret_key_here
    restart: unless-stopped