# Generated by Django 5.1.7 on 2025-04-11 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ADMIN', 'Admin'), ('MANAGER', 'Manager'), ('ENGINEER', 'Engineer')], default='ADMIN', max_length=10)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_made', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_meters', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meter.meter')),
                ('previous_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='meter.meterassignment')),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
    ]
