# Generated by Django 5.1.7 on 2025-04-12 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0002_meterassignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterassignment',
            old_name='assigned_to',
            new_name='engineer',
        ),
        migrations.RenameField(
            model_name='meterassignment',
            old_name='assigned_by',
            new_name='manager',
        ),
    ]
