# Generated by Django 5.1.7 on 2025-04-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meter', '0006_alter_meter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterdata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
